[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trajectory-container-tools"
dynamic = ["version"]

description = "Trajectory Container Tools for Robotic Deep Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "RedLeader Research", email = "research@redleader.com" }
]
keywords = ["robotics", "reinforcement-learning", "trajectory", "dataclass"]
classifiers = [
    "Development Status :: 3 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "tqdm",
    "deprecated",
]

[project.optional-dependencies]
ros = [
    "rosbags",
]
dev = [
    "pytest",
    "pytest-mock",
    "pytest-xdist",
    "pytest-benchmark",
    "pytest-env",
    "pytest-randomly",
    "pytest-deprecate",
    "black",
    "flake8",
]

[tool.setuptools.packages.find]
# Recommended Following a src-layout repository structure where "." is the repository root
# and "src" is the source code location.
where = [
    ".",
    "src"
]
# Recommended directory exclusion to prevent build faillure for cases where python projects
# are collocated along side ros2 projects in the same repository.
exclude = [
    "*/build",
    "*/install",
    "*/log"
]
