[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trajectory-container-tools"
dynamic = ["version"]
description = "Trajectory Container Tools for Robotic Deep Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Luc Coupal", email = "luc.coupal.1@ulaval.ca" }
]
keywords = [
    "trajectory",
    "dataclasses",
    "sequential-decision-making-problem",
    "robotics",
    "deep-reinforcement-learning"
]
classifiers = [
    "Development Status :: 3 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "tqdm",
    "deprecated",
]

[project.optional-dependencies]
ros = [
    "rosbags",
]
dev = [
    "pytest",
    #"pytest<8", # <-- Note on why its pinned: `launch_testing` ROS2 pytest plugin uses the legacy `pytest_pycollect_makemodule(path, parent)` hook signature, which pytest 8.x no longer supports (backward-compat shim removed). Ref https://github.com/ros2/launch/issues/979
    "pytest-mock",
    "pytest-xdist",
    "pytest-benchmark",
    "pytest-env",
    "pytest-randomly",
    "pytest-deprecate",
    "black",
    "flake8",
    "coverage",
]

[tool.setuptools.packages.find]
# Recommended Following a src-layout repository structure where "." is the repository root
# and "src" is the source code location.
where = [
    ".",
    "src"
]
# Recommended directory exclusion to prevent build faillure for cases where python projects
# are collocated along side ros2 projects in the same repository.
exclude = [
    "*/build",
    "*/install",
    "*/log"
]

[tool.coverage.run]
# Note: run using
#   $ coverage run -m pytest \
#       --config-file=/ros2_ws/src/trajectory-container-tools/tests/pytest.no_xdist.ini \
#       && coverage report
source = ["src/trajectory_container_tools"]
data_file = "reports/coverage/.coverage"
omit = [
    "*/tests/*",
    "*/test_*.py",
    "*/*plot*.py",
    "*/optimization.py",
]
branch = true


[tool.coverage.report]
fail_under = 80
ignore_errors = true

# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",
    "if debuging:",
    "if debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
    ]


[tool.coverage.xml]
output = "reports/coverage/coverage.xml"

[tool.coverage.html]
directory = "reports/coverage/htmlcov"

